export default [
  "Aerospace Engineering",
  "Agricultural and Environmental Plant Sciences",
  "Agricultural Business",
  "Agricultural Communication",
  "Agricultural Science",
  "Agricultural Systems Management",
  "Animal Science",
  "Anthropology and Geography",
  "Architectural Engineering",
  "Architecture",
  "Art and Design",
  "Biochemistry",
  "Biological Sciences",
  "Biomedical Engineering",
  "BioResource and Agricultural Engineering",
  "Business Administration",
  "Chemistry",
  "Child Development",
  "City and Regional Planning",
  "Civil Engineering",
  "Communication Studies",
  "Comparative Ethnic Studies",
  "Computer Engineering",
  "Computer Science",
  "Construction Management",
  "Dairy Science",
  "Economics",
  "Electrical Engineering",
  "English",
  "Environmental Earth and Soil Sciences",
  "Environmental Engineering",
  "Environmental Management and Protection",
  "Food Science",
  "Forestry and Natural Resources",
  "General Engineering",
  "Graphic Communication",
  "History",
  "Industrial Engineering",
  "Industrial Technology and Packaging",
  "Interdisciplinary Studies",
  "Journalism",
  "Kinesiology",
  "Landscape Architecture",
  "Liberal Arts and Engineering Studies",
  "Liberal Studies",
  "Manufacturing Engineering",
  "Marine Sciences",
  "Materials Engineering",
  "Mathematics",
  "Mechanical Engineering",
  "Microbiology",
  "Music",
  "Nutrition",
  "Philosophy",
  "Physics",
  "Physics",
  "Political Science",
  "Public Health",
  "Psychology",
  "Recreation, Parks, and Tourism Administration",
  "Sociology",
  "Software Engineering",
  "Spanish",
  "Statistics",
  "Theatre Arts",
  "Wine and Viticulture"
];
